#!/usr/bin/env bash
# Script that configures an Nginx server
# to a custom 404 Page
apt-get update -y
apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sed -i '/listen 80 default_server/a error_page 404 /custom_404.html;\nlocation = /custom_404.html {\n\troot /home/ubuntu/html;\n\tinternal;\n}' /etc/nginx/sites-available/default
service nginx restart
