#!/usr/bin/env bash
#Write a Bash script that gives you information about the school file
for ((i = 1; i <= 100; i++)); do
	if [ $((i % 3)) == 0 ] && [ $((i % 5)) == 0 ]; then
		echo "FizzBuzz"
	elif [ $((i % 3)) == 0 ]; then
		echo "Fizz"
	elif [ $((i % 5)) == 0 ]; then
		echo "Buzz"
	else
		echo "$i"
	fi
done
