#!/usr/bin/env bash
#Write a Bash script that gives you information about the school file
FILE=./school
if test -f "$FILE"; then
	echo "school file exists"
if test -s "$FILE";
echo "school file is not empty"
else
	echo "school file does not exist"
fi
