#!/usr/bin/env bash
# Bash script that configures the container to run nginx as nginx user
pkill -f apache2
chown -R nginx:nginx /etc/nginx
chmod 700 /etc/nginx/nginx.conf
sed -i 's/80/8080/' /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
