#!/usr/bin/env bash
# Bash script that configures the container to run nginx as nginx user but in less lines
pkill -f apache2
chmod 777 /etc/nginx/nginx.conf
sed -i 's/80/8080/' /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
